# Configuration inspired by https://thevaluable.dev/tmux-config-mouseless/
# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# Increase history limit
set -g history-limit 100000

# Change prefix to C - Space
unbind C-b
set -g prefix C-Space

# split panes using | and -
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file 
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# Change base index for windows
set -g base-index 1
set-window-option -g pane-base-index 1

# Use vi keys in copy mode
set-window-option -g mode-keys vi

# Change selection keys to vi keys and use system clipboard
## NOTE need either xclip or wl-clipboard

unbind -T copy-mode-vi Space; #Default for begin-selection
unbind -T copy-mode-vi Enter; #Default for copy-selection

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy" # for wayland
#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy" # for X11


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "nordtheme/tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
