# Configuration inspired by https://thevaluable.dev/tmux-config-mouseless/
# https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# Fix Vim ESC delay (tmux 3.5+ already defaults to 10ms)
set -sg escape-time 0

# Increase history limit
set -g history-limit 50000

# Change base index for windows
set -g base-index 1
set-window-option -g pane-base-index 1

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Enable focus events for vim autoread
set -g focus-events on

# Change prefix to C - Space
unbind C-b
set -g prefix C-Space

# Aggressive resize for multi-client
setw -g aggressive-resize on

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file 
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.tmux.conf"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Resize panes using Alt-Shift-arrow without prefix
bind -n M-S-Left resize-pane -L 2
bind -n M-S-Right resize-pane -R 2
bind -n M-S-Up resize-pane -U 2
bind -n M-S-Down resize-pane -D 2

# don't rename windows automatically
set-option -g allow-rename off

# Use vi keys in copy mode
set-window-option -g mode-keys vi

# Change selection keys to vi keys and use system clipboard
## NOTE need either xclip or wl-clipboard

# Enter to copy mode
bind Enter copy-mode

# Exit from copy mode
bind -T copy-mode-vi Escape send-keys -X cancel

unbind -T copy-mode-vi Space; #Default for begin-selection
unbind -T copy-mode-vi Enter; #Default for copy-selection

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy" # for wayland


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect' 
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin "nordtheme/tmux"

# Plugin settings
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# Support XDG ~/.config/tmux/plugins/tpm as well as standard ~/.tmux/plugins/tpm
if "test -f ~/.config/tmux/plugins/tpm/tpm" \
   "run '~/.config/tmux/plugins/tpm/tpm'" \
   "run '~/.tmux/plugins/tpm/tpm'"
